/home/gpli/llvm-2.9-build/tools/llvmc/src/Release/Main.o \
 /home/gpli/llvm-2.9-build/tools/llvmc/src/Release/Main.d: \
 /home/gpli/llvm-2.9/tools/llvmc/src/Main.cpp \
 /home/gpli/llvm-2.9-build/tools/llvmc/src/AutoGenerated.inc \
 /home/gpli/llvm-2.9/include/llvm/CompilerDriver/BuiltinOptions.h \
 /home/gpli/llvm-2.9/include/llvm/Support/CommandLine.h \
 /home/gpli/llvm-2.9/include/llvm/Support/type_traits.h \
 /home/gpli/llvm-2.9/include/llvm/Support/Compiler.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/SmallVector.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/Twine.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/StringRef.h \
 /home/gpli/llvm-2.9-build/include/llvm/Support/DataTypes.h \
 /home/gpli/llvm-2.9/include/llvm/CompilerDriver/CompilationGraph.h \
 /home/gpli/llvm-2.9/include/llvm/CompilerDriver/Tool.h \
 /home/gpli/llvm-2.9/include/llvm/CompilerDriver/Action.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/IntrusiveRefCntPtr.h \
 /home/gpli/llvm-2.9/include/llvm/Support/Casting.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/StringSet.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/StringMap.h \
 /home/gpli/llvm-2.9/include/llvm/Support/Allocator.h \
 /home/gpli/llvm-2.9/include/llvm/Support/AlignOf.h \
 /home/gpli/llvm-2.9/include/llvm/Support/MathExtras.h \
 /home/gpli/llvm-2.9/include/llvm/Support/SwapByteOrder.h \
 /home/gpli/llvm-2.9/include/llvm/Support/Path.h \
 /home/gpli/llvm-2.9/include/llvm/Support/PathV1.h \
 /home/gpli/llvm-2.9/include/llvm/Support/TimeValue.h \
 /home/gpli/llvm-2.9/include/llvm/Support/PathV2.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/SmallString.h \
 /home/gpli/llvm-2.9/include/llvm/ADT/GraphTraits.h \
 /home/gpli/llvm-2.9/include/llvm/CompilerDriver/Error.h \
 /home/gpli/llvm-2.9/include/llvm/Support/raw_ostream.h \
 /home/gpli/llvm-2.9/include/llvm/CompilerDriver/Main.inc \
 /home/gpli/llvm-2.9/include/llvm/CompilerDriver/Main.h

/home/gpli/llvm-2.9-build/tools/llvmc/src/AutoGenerated.inc:

/home/gpli/llvm-2.9/include/llvm/CompilerDriver/BuiltinOptions.h:

/home/gpli/llvm-2.9/include/llvm/Support/CommandLine.h:

/home/gpli/llvm-2.9/include/llvm/Support/type_traits.h:

/home/gpli/llvm-2.9/include/llvm/Support/Compiler.h:

/home/gpli/llvm-2.9/include/llvm/ADT/SmallVector.h:

/home/gpli/llvm-2.9/include/llvm/ADT/Twine.h:

/home/gpli/llvm-2.9/include/llvm/ADT/StringRef.h:

/home/gpli/llvm-2.9-build/include/llvm/Support/DataTypes.h:

/home/gpli/llvm-2.9/include/llvm/CompilerDriver/CompilationGraph.h:

/home/gpli/llvm-2.9/include/llvm/CompilerDriver/Tool.h:

/home/gpli/llvm-2.9/include/llvm/CompilerDriver/Action.h:

/home/gpli/llvm-2.9/include/llvm/ADT/IntrusiveRefCntPtr.h:

/home/gpli/llvm-2.9/include/llvm/Support/Casting.h:

/home/gpli/llvm-2.9/include/llvm/ADT/StringSet.h:

/home/gpli/llvm-2.9/include/llvm/ADT/StringMap.h:

/home/gpli/llvm-2.9/include/llvm/Support/Allocator.h:

/home/gpli/llvm-2.9/include/llvm/Support/AlignOf.h:

/home/gpli/llvm-2.9/include/llvm/Support/MathExtras.h:

/home/gpli/llvm-2.9/include/llvm/Support/SwapByteOrder.h:

/home/gpli/llvm-2.9/include/llvm/Support/Path.h:

/home/gpli/llvm-2.9/include/llvm/Support/PathV1.h:

/home/gpli/llvm-2.9/include/llvm/Support/TimeValue.h:

/home/gpli/llvm-2.9/include/llvm/Support/PathV2.h:

/home/gpli/llvm-2.9/include/llvm/ADT/SmallString.h:

/home/gpli/llvm-2.9/include/llvm/ADT/GraphTraits.h:

/home/gpli/llvm-2.9/include/llvm/CompilerDriver/Error.h:

/home/gpli/llvm-2.9/include/llvm/Support/raw_ostream.h:

/home/gpli/llvm-2.9/include/llvm/CompilerDriver/Main.inc:

/home/gpli/llvm-2.9/include/llvm/CompilerDriver/Main.h:
